import dhcp-4.2.5-36.el7

diff --git a/SOURCES/dhclient-script b/SOURCES/dhclient-script
--- a/SOURCES/dhclient-script
+++ b/SOURCES/dhclient-script
@@ -44,14 +44,6 @@ logmessage() {
     logger -p ${LOGFACILITY}.${LOGLEVEL} -t "NET" "dhclient: ${msg}"
 }
 
-if [ -x /sbin/restorecon ]; then
-    fix_context() {
-        /sbin/restorecon ${1} >/dev/null 2>&1
-    }
-else
-    fix_context() { :; }
-fi
-
 eventually_add_hostnames_domain_to_search() {
 # For the case when hostname for this machine has a domain that is not in domain_search list
 # 1) get a hostname with `ipcalc --hostname` or `hostname`
@@ -145,8 +137,6 @@ make_resolv_conf() {
         if [ -n "${search}" ]; then
             eventually_add_hostnames_domain_to_search "${search}"
         fi
-
-        fix_context /etc/resolv.conf
     elif [ -n "${new_dhcp6_name_servers}" ] ||
          [ -n "${new_dhcp6_domain_search}" ]; then
         rscf="$(mktemp ${TMPDIR:-/tmp}/XXXXXX)"
@@ -189,8 +179,6 @@ make_resolv_conf() {
         if [ -n "${search}" ]; then
             eventually_add_hostnames_domain_to_search "${search}"
         fi
-
-        fix_context /etc/resolv.conf
     fi
 }
 
@@ -274,17 +262,9 @@ is_router_reachable() {
     mysubnet="$(get_network_address ${new_ip_address} ${new_subnet_mask})"
 
     if [ ! "${routersubnet}" = "${mysubnet}" ]; then
-        ip -4 route add ${router}/32 dev ${interface}
-        if [ $? -eq 0 ]; then
-            if ping -q -c1 -w2 -I ${interface} ${router}; then
-                return 0
-            else
-                logmessage "DHCP router ${router} is unreachable on DHCP subnet ${mysubnet} router subnet ${routersubnet}"
-                ip route del ${router}/32 dev ${interface}
-                return 1
-            fi
-        else
-            logmessage "failed to create host router for unreachable router ${router} not on subnet ${mysubnet}"
+        ip -4 route replace ${router}/32 dev ${interface}
+        if [ "$?" -ne 0 ]; then
+            logmessage "failed to create host route for ${router}"
             return 1
         fi
     fi
@@ -537,7 +517,6 @@ dhconfig() {
         if [ -e ${tzfile} ]; then
             cp -fp ${tzfile} /etc/localtime
             touch /etc/localtime
-            fix_context /etc/localtime
         fi
     fi
 
@@ -558,22 +537,30 @@ add_ipv6_addr_with_DAD() {
             for i in $(seq 5); do
                 sleep 1 # give the DAD some time
 
+                addr=$(ip -6 addr show dev ${interface} \
+                       | grep ${new_ip6_address}/${new_ip6_prefixlen})
+
                 # tentative flag == DAD is still not complete
-                tentative=$(ip -6 addr show dev ${interface} tentative \
-                           | grep ${new_ip6_address}/${new_ip6_prefixlen})
+                tentative=$(echo "${addr}" | grep tentative)
                 # dadfailed flag == address is already in use somewhere else
-                dadfailed=$(ip -6 addr show dev ${interface} dadfailed \
-                           | grep ${new_ip6_address}/${new_ip6_prefixlen})
+                dadfailed=$(echo "${addr}" | grep dadfailed)
 
                 if [ -n "${dadfailed}" ] ; then
-                    #ip -6 addr del ${new_ip6_address}/${new_ip6_prefixlen} dev ${interface}
+                    # address was added with valid_lft/preferred_lft 'forever', remove it
+                    ip -6 addr del ${new_ip6_address}/${new_ip6_prefixlen} dev ${interface}
                     exit_with_hooks 3
                 fi
                 if [ -z "${tentative}" ] ; then
-                    # DAD is over
-                    return 0
+                    if [ -n "${addr}" ]; then
+                        # DAD is over
+                        return 0
+                    else
+                        # address was auto-removed (or not added at all)
+                        exit_with_hooks 3
+                    fi
                 fi
             done
+            return 0
 }
 
 dh6config() {
@@ -596,18 +583,16 @@ dh6config() {
             ;;
 
         RENEW6|REBIND6)
-            if [ -z "${new_ip6_address}" ] ||
-               [ -z "${new_ip6_prefixlen}" ]; then
-                exit_with_hooks 2
-            fi
-
-            if [  ! "${new_ip6_address}" = "${old_ip6_address}" ]; then
-                add_ipv6_addr_with_DAD
-            else # only update address lifetimes
-                ip -6 addr change ${new_ip6_address}/${new_ip6_prefixlen} \
-                   dev ${interface} scope global valid_lft ${new_max_life} \
-                                             preferred_lft ${new_preferred_life}
-            fi
+            if [[ -n "${new_ip6_address}" ]] &&
+               [[ -n "${new_ip6_prefixlen}" ]]; then
+               if [[  ! "${new_ip6_address}" = "${old_ip6_address}" ]]; then
+                   add_ipv6_addr_with_DAD
+               else # only update address lifetimes
+                   ip -6 addr change ${new_ip6_address}/${new_ip6_prefixlen} \
+                      dev ${interface} scope global valid_lft ${new_max_life} \
+                                                preferred_lft ${new_preferred_life}
+               fi
+             fi
 
             if [ ! "${new_dhcp6_name_servers}" = "${old_dhcp6_name_servers}" ] ||
                [ ! "${new_dhcp6_domain_search}" = "${old_dhcp6_domain_search}" ]; then
@@ -704,6 +689,15 @@ case "${reason}" in
 
         # remove any stale addresses from aborted clients
         ip -6 addr flush dev ${interface} scope global permanent
+
+        # we need a link-local address to be ready (not tentative)
+        for i in $(seq 50); do
+            linklocal=$(ip -6 addr show dev ${interface} scope link)
+            # tentative flag means DAD is still not complete
+            tentative=$(echo "${linklocal}" | grep tentative)
+            [[ -n "${linklocal}" && -z "${tentative}" ]] && exit_with_hooks 0
+            sleep 0.1
+        done
 
         exit_with_hooks 0
         ;;
